version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: karina127
      POSTGRES_DB: myPortfolio
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:karina127@db:5432/myPortfolio
      JWT_SECRET: testsecret
      CLIENT_URL: http://localhost:5173
    depends_on:
      - db

volumes:
  db-data:
    driver: local